import './globals.css';
import Nav from '../components/shared/Nav';
import Footer from '../components/shared/Footer';
import Bg from '../utils/Bg';

export const metadata = {
  title: 'KSM IoT UPNVJ',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative min-h-screen flex flex-col">
        <Nav />
        <Bg />
        {children}
        <Footer />
      </body>
    </html>
  );
}
